#
# Makefile for the CS 105 File Systems Homework
#
# Eleanor Birrell, Anthony Clark
# Pomona College
# April 22, 2022
#
SHELL = /bin/sh

all: fs

fs: fs.c
	gcc -std=c99 -o fs -g fs.c

clean:
	rm -rf fs
